source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.3'

# Image saving and processing
gem 'paperclip', '~> 5.1'
# paperclip optimization module
gem 'paperclip-optimizer'
