source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.3'

# Allow `PokemonGoLocation` model to be voted on upvote/downvote by `PokemonGoUser`.
# Read more: https://github.com/ryanto/acts_as_votable
gem 'acts_as_votable'

# distance calculation and geocoding
gem 'geokit-rails'
